version: '3.7'
services:
  backend:
    image: node:10-alpine
    container_name: backend
    build: ./backend/
    command: "npm run start"
    environment:
      PORT: 4100
    volumes:
      - ./backend:/app
    ports:
      - "4100:4100"

  database:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database:
    driver: local
