version: '3.7'
services:
  database:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: node:10-alpine
    container_name: backend
    volumes:
      - ./backend/:/app
    working_dir: /app
    command: sh ./start.sh
    environment:
      PORT: 4100
    ports:
      - "4100:4100"

  frontend:
    image: node:10-alpine
    container_name: frontend
    volumes:
      - ./frontend/:/app
    working_dir: /app
    command: sh start.sh
    ports:
      - "4200:4200"

volumes:
  database:
    driver: local
